[package]
name = "part3"
version = "0.1.0"
authors = ["irfan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib_part3 =  { path = "../lib_part3"}